[package]
authors = ["Sascha Grunert <mail@saschagruenrt.de>"]
categories = ["web-programming"]
description = "A web application completely written in Rust"
documentation = "https://docs.rs/webapp"
homepage = "https://github.com/saschagrunert/webapp.rs"
keywords = ["web", "app", "website", "webapp"]
license = "MIT"
name = "webapp"
readme = "README.md"
repository = "https://github.com/saschagrunert/webapp.rs"
version = "0.2.0"
[[bin]]
name = "frontend"
path = "src/frontend/main.rs"
required-features = ["frontend"]

[[bin]]
name = "backend"
path = "src/backend/main.rs"
[badges.appveyor]
branch = "master"
repository = "saschagrunert/webapp.rs"
service = "github"

[badges.travis-ci]
branch = "master"
repository = "saschagrunert/webapp.rs"

[build-dependencies]
capnpc = "0.8.9"
failure = "0.1.1"
sass-rs = "0.2.1"

[dependencies]
capnp = "0.8.17"
failure = "0.1.1"

[dependencies.actix]
optional = true
version = "0.6.0"

[dependencies.actix-web]
features = ["alpn"]
optional = true
git = "https://github.com/actix/actix-web"

[dependencies.env_logger]
optional = true
version = "0.5.10"

[dependencies.jsonwebtoken]
optional = true
version = "4.0.1"

[dependencies.log]
optional = true
version = "0.4.2"

[dependencies.openssl]
optional = true
version = "0.10.10"

[dependencies.serde]
optional = true
version = "1.0.66"

[dependencies.serde_derive]
optional = true
version = "1.0.66"

[dependencies.stdweb]
optional = true
version = "0.4.6"

[dependencies.time]
optional = true
version = "0.1.40"

[dependencies.yew]
git = "https://github.com/DenisKolodin/yew"
optional = true

[features]
default = ["actix", "actix-web", "env_logger", "jsonwebtoken", "log", "openssl", "serde", "serde_derive", "time"]
frontend = ["stdweb", "yew"]
